apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
