apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
      - name: app
        env:
        - name: REPO
          value: "https://github.com/cycloid-community-catalog/docs-step-by-step-stack"
        - name: COMMIT
          value: "origin/master"
